#!/usr/bin/env bash
#install nginx server on remote machine
apt-get -y update
apt-get -y install nginx
chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
