#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
sudo apt-get -y update
sudo apt-get -y install haproxy

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend ilovecoding.tech
        bind *:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 432556-web-01 100.26.20.138:80
        server 432556-web-02 34.201.164.67:80
' >> /etc/haproxy/haproxy.cfg

service haproxy restart
