#!/usr/bin/env bash
#configures a ufw firewall to block all incoming traffic
#except for TCP ports 22, 443 and 80.
sudo apt-get install ufw
ufw default deny incoming
ufw default allow outgoingsudo ufw enable
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
